"""The frozen surface of ``pyradioss/implicit/`` — Task P1.6.

What this file is for
---------------------
``pyradioss/implicit/`` carries roughly 25k LOC that upstream OpenRadioss does
**not** have: the implicit Newton / arc-length branch (M8–M15), modal and
complex-modal superposition (M16–M18), random / PSD response and response
spectra (M19), and the spectral-fatigue tower (M20–M34). That extra surface is
why the subsystem has to be *pinned*, not merely documented: the moment a file
can be added or deleted without consequence, the record of what the project is
silently wrong.

The binding decision, encoded here
----------------------------------
* **Decision (maintainer, 2026-10-02)** — recorded in
  ``plan/00_ORCHESTRATION.md`` §3: **keep, but quarantine behind extras.**
* Consequence, binding on every phase: **no new features** under
  ``pyradioss/implicit/`` except what Phase 15
  (``15_phase14_implicit_parity.md``) needs for parity with upstream
  ``engine/source/implicit``.
* Every module listed below must remain **importable and green** for the whole
  program. A phase that breaks one is a phase that does not merge.
* The optional linear-solver backends (CHOLMOD via ``sksparse``, MUMPS via
  ``python-mumps``) keep their existing optional guards. Do **not** promote them
  to hard dependencies.

Provenance of the list below
----------------------------
* **Method:** generated, not typed. It came from a one-shot **census** of the
  live package directory with ``pkgutil.iter_modules`` over
  ``pyradioss.implicit.__path__``, keeping names that do not begin with an
  underscore. Hand-typing the names is the failure mode this file exists to
  prevent: one typo would read as a spurious "added"/"removed" verdict forever.
* **Census taken:** 2026-10-04, from the tree at commit ``cf046a3``
  (``docs(gate): the licence gate now meets the agent in AGENTS.md and both
  plan files``), branch ``plan/p1``.
* **Count:** **33** public modules (``__init__.py`` excluded by the
  underscore rule). ``plan/02_phase1_foundation.md`` Task P1.6 wrote "37 module
  names" from a snapshot taken before this tree; the discrepancy is recorded in
  ``tests/test_p1_frozen_implicit.py``'s header and in the Task P1.6 report, and
  **the live tree wins** — the plan figure is a stale snapshot, not a
  requirement. There is no missing module: ``git log --diff-filter=D --
  pyradioss/implicit/`` is empty, so nothing was ever deleted from this package
  and the 33 names are simply the 33 that exist.
* **Scope rule:** names beginning with ``_`` are outside the census. That
  excludes ``__init__`` (the package's own facade) and this file — a list
  containing its own module would make the digest self-referential.

How the digest is computed, and how a legitimate change is made
----------------------------------------------------------------
``FROZEN_SURFACE_SHA256`` is a digest **over the SORTED names**, one per line,
with a trailing newline::

    sha256("\\n".join(sorted(names)) + "\\n").hexdigest()

It is pinned as a literal, not computed at import, so it is a checksum rather
than an echo of the tree. ``tests/test_p1_frozen_implicit.py::
test_frozen_surface_sha256_is_recomputable`` recomputes it from the **live**
``pkgutil`` scan and compares — an unverified constant would be decoration.

* **ADDING a name is a deliberate act and requires the maintainer's approval.**
  It is not a mechanical consequence of writing a new file, and it is not
  something an agent may grant itself. With approval recorded, the legitimate
  procedure is: regenerate this file's ``_SORTED_MODULE_NAMES`` from a live
  ``pkgutil.iter_modules`` scan and replace ``FROZEN_SURFACE_SHA256`` with the
  digest that same scan prints. Edit **this file** (``_frozen_surface.py``)
  together with the new module, in one commit whose message quotes the approval
  and the before/after digest.
* **REMOVING a name is a hard failure**, never a list edit. ``test_implicit_
  surface_is_frozen`` reports it under ``"removed"``, and the list is not to be
  edited to make it pass. A removal is either a mistake or a decision that
  re-opens the quarantine decision itself, and both outrank a test edit.
* No other file may be edited to make either verdict change: not the census
  rule, not the test, not the plan's number.

Interfaces
----------
``FROZEN_MODULES: frozenset[str]`` — the 33 module names, above.
``FROZEN_SURFACE_SHA256: str`` — the sorted-names digest, above.
``_surface_digest(names) -> str`` — the recipe as code, so the module and the
test cannot drift into computing two different things over the same data.
"""

from __future__ import annotations

import hashlib
from typing import Iterable

#: Generated by a pkgutil census on 2026-10-04 (see the module docstring).
#: Sorted so a diff of this file reads as an ordered change, not a reshuffle.
_SORTED_MODULE_NAMES: tuple[str, ...] = (
    "assembly",
    "bfgs",
    "buckling",
    "complex_modal",
    "constraints",
    "contact",
    "convergence",
    "damping_matrix",
    "dofmap",
    "dynamics",
    "evolutionary_fatigue",
    "evolutionary_multi_input",
    "followerload",
    "freq_evolutionary_multi_input",
    "joint_evolutionary_fatigue",
    "joint_nongaussian_fatigue",
    "linesearch",
    "linsolve",
    "modal",
    "modal_response",
    "multi_input_fatigue",
    "multi_input_response",
    "multiaxial_fatigue",
    "nongaussian_fatigue",
    "nongaussian_wigner_ville_fatigue",
    "nonproportional_fatigue",
    "nonstationary_fatigue",
    "random_response",
    "response_spectrum",
    "spectral_fatigue",
    "spectral_nonproportional_fatigue",
    "statics",
    "wigner_ville_fatigue",
)

#: The frozen surface: the public module names of ``pyradioss/implicit/``.
FROZEN_MODULES: frozenset[str] = frozenset(_SORTED_MODULE_NAMES)

#: sha256 over the SORTED names, one per line, trailing newline.
FROZEN_SURFACE_SHA256: str = (
    "60611cce763b4bb9acdb34eb4c98377ea2d9b80f7091fdde339e12aaa84b165a"
)


def _surface_digest(names: Iterable[str]) -> str:
    """The documented recipe as code: ``sha256`` of the sorted names, joined by
    newlines with a trailing newline. Order of the input is irrelevant — the
    sort is inside the function, so a caller cannot produce a different digest
    by handing the names over unsorted."""
    payload = "\n".join(sorted(names)) + "\n"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()