# -*- coding: utf-8 -*-
"""
pyradioss.input.keywords - Starter keyword readers.

Split out of ``pyradioss/input/starter_keywords.py`` (Task P1.5). The public
surface is unchanged: ``parse_starter_deck``, ``read_starter_deck``,
``KEYWORD_PARSERS`` and every ``read_*`` reader are reachable from here, and
the old module path stays as a deprecation shim for one release cycle.

Layout
------
``dispatch.py``  keyword -> parser table and the block loop.
``geometry``, ``elements``, ``materials``, ``properties``, ``interfaces``,
``constraints``, ``loads``, ``conditions``, ``groups``, ``output``, ``misc``
                  the readers, one module per keyword family.

Cross-module references
-----------------------
The readers call each other freely - ``read_mat`` dispatches to the
``read_mat_law*`` readers, ``read_fail`` to the ``read_fail_*`` readers, and
so on - and some of those relationships are cyclic, so a reader module cannot
just ``from .materials import read_mat_law1`` at import time. Every family
module is therefore imported first and the readers are published into each
sibling module's globals once, by :func:`_bind_cross_module_references`. A
module-local definition always wins over a published one.
"""

from __future__ import annotations

from __future__ import annotations

from typing import Callable, Dict, List, Optional, Tuple, Union
import os

import numpy as np

from ...common.messages import MessageLog
from ...common.tables import FunctTable
from ...model.entities import (
    AddedMass, BoundaryCondition, Box, ConcentratedLoad, Damping, Gravity,
    CentrifugalLoad, ImposedAcceleration, ImposedDisplacement, ImposedTemperature, ImposedVelocity, InitialVelocity, Interface, Line,
    Material, Mpc, NodeGroup, Part, PressureLoad, Property, Random, Rbe3, RigidBody,
    RigidWall, Section, MonitoredVolume, Sensor, Subdomain, Submodel, Surface, Table, THRequest, Xref,
    DetonatorPoint, DetonatorPlane,
    ConvectionLoad, InivolContainer, InitialVolume,
    RadiationLoad, ImposedFlux, InitialTemperature,
    InitialBrickState, InitialShellState,
    InitialTrussState, InitialBeamState, InitialSpringState,
    BcsNrf, BcsWall, RigidLink, CylJoint, GJoint, GeneralJoint,
    MergeNode, MergeRbody, IniCrack, IniCrackSegment, LaserLoad,
    PcylLoad, PfluidLoad, Preload, PreloadAxial, DampInter, DampRange,
    AnalyGlobal, UpwindGlobal, CaaControl,
    Gauge, Cluster, ExtLink, FxBody, IniGrav, IniMap1D, IniMap2D, IniStateFile,
    MonvolPres, MonvolGas, MonvolCommu1, MonvolLFluid, LeakMat,
    MonvolAirbag, MonvolAirbagJet, MonvolAirbagVent, MonvolCommu, MonvolPart,
    DampGlobal, DampPart, TransformProjection, TransformFrame,
    LoadGravity, LoadBody, LoadTherm, EulerBcs, HeatBcs,
    RwallBox, RwallCone, SectBox, SectCut,
    InivelPart, InivelSph, DetLine, DetCirc, IniMap3D, SetGeneric,
    AleGrid, AleLink, AleSolver, AleClose,
    Retractor, Slipring, UserWindow,
    Drape, IniBriEref, IncludeDyna, MonvolFvmBag1, MonvolFvmbag,
    FvmInjector, FvmVent, FvmOrifice, FvmPorousSurface, FvmChamber,
    GaugePoint, SphGlo, AnalyOptions, AleCfdSph,
    FailOrthBiquad, SlipringShell,
    Upbeam, RelaxSystem, MonvolComm,
)
from ...model.model import Model
from ...model.skew import SkewFrame
from .. import mat_reader
from ..card_layouts import LAYOUTS
from ..card_layouts import CARD_LAYOUTS
from ..card_layouts import split_fixed
from ..deck_reader import Card, KeywordBlock, _to_float, parse_fortran_float


# ----------------------------------------------------------------------------
# Small helpers shared by the parsers
# ----------------------------------------------------------------------------

from . import conditions
from . import constraints
from . import dispatch
from . import elements
from . import geometry
from . import groups
from . import interfaces
from . import loads
from . import materials
from . import misc
from . import output
from . import properties
from .dispatch import (
    ENGINE_KEYWORDS_IGNORE,
    KEYWORD_PARSERS,
    MATERIAL_DISPATCH,
    ParsedStarterModel,
    parse_starter_deck,
    read_starter_deck,
)

_READER_MODULES = (
    conditions, constraints, elements, geometry, groups, interfaces,
    loads, materials, misc, output, properties,
)


def _bind_cross_module_references() -> None:
    """Publish every top-level name of each family module into its siblings.

    The readers were written when they all shared one module namespace, and
    the split did not rewrite a single call site, so a reader must still be
    able to resolve a sibling -- another reader, or a shared card constant
    like ``_IMP_DOF`` -- by bare name at call time. Some of those references
    are cyclic, which is why they cannot be plain module-level imports.
    """
    reserved = frozenset(
        ("__name__", "__doc__", "__file__", "__package__", "__loader__",
         "__spec__", "__builtins__", "__all__", "__path__", "__cached__"))
    registry = {}
    for module in _READER_MODULES:
        for name, obj in vars(module).items():
            if name not in reserved:
                registry[name] = obj
    for module in _READER_MODULES:
        namespace = module.__dict__
        for name, obj in registry.items():
            namespace.setdefault(name, obj)
    return None

_bind_cross_module_references()


from .geometry import (  # noqa: F401
    read_ale_grid, read_box, read_cyl_joint, read_cyl_joint_m209, read_frame, read_frame_nod,
    read_line, read_node, read_parallel_joint, read_skew, read_surf, read_surf_surf,
    read_transform,
)

from .elements import (  # noqa: F401
    read_beam, read_bric20, read_brick, read_def_shell, read_def_solid, read_drape,
    read_eng_accel, read_eng_ale, read_eng_ale_energy, read_eng_barocaloric_energy,
    read_eng_bulk_viscosity, read_eng_contact_energy, read_eng_coriolis_energy,
    read_eng_damp, read_eng_density, read_eng_deviatoric_energy,
    read_eng_dielectric_loss_energy, read_eng_disp, read_eng_effective_stress,
    read_eng_elastocaloric_energy, read_eng_electrocaloric_energy,
    read_eng_electrohydrodynamic_energy, read_eng_electromagnetomechanical_resonance_energy,
    read_eng_electrorheological_energy, read_eng_electrostrictive_energy,
    read_eng_electrothermoflexoexcitonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralantimeronplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralantiskyrmionplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralanyonplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralaxionicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralbimeronplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralblochpointplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralbobberplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiraldyonicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralexcitonicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralhedgehogplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralholonplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralhopfionplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralinstantonplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralmagnonicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralmajoranaplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralmeronplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralmonopoleplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralorbitonplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralparamagnonplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralphononicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralplasmononplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralskyrmioniumplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralskyrmionplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralsolitonplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralsphaleronplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralspinonplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralspinplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiraltoronplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetochiralvortexplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoexcitonicmagnonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoexcitonicmagnonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoexcitonicmagnonpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoexcitonicphononicmagnonpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoexcitonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoexcitonicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoexcitonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetomagnonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetomagnonicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetomagnonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetophononicexcitonicmagnonicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetophononicexcitonicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetophononicmagnonicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetophononicmagnonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetophononicmagnonpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetophononicplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetophononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicexcitonicmagnonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicexcitonicmagnonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicexcitonicmagnonpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicexcitonicphononicmagnonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicexcitonicphononicmagnonpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicexcitonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicmagnonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicmagnonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicmagnonpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicphononicmagnonpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnetoplasmonicpolaritonic_resonance_energy,
    read_eng_electrothermoflexomagnonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexoplasmonicexcitonicmagnonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexoplasmonicexcitonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexoplasmonicmagnonicphononicpolaritonic_resonance_energy,
    read_eng_electrothermoflexoplasmonicphononicpolaritonic_resonance_energy,
    read_eng_energy, read_eng_entropy, read_eng_entropy_production,
    read_eng_exciton_polariton_energy, read_eng_ext_work, read_eng_ferroelectric_energy,
    read_eng_flexoelectric_energy, read_eng_flexoelectroacoustic_resonance_energy,
    read_eng_flexoelectromagnetic_resonance_energy, read_eng_flexomagnetic_energy,
    read_eng_flexomagnetoacoustic_resonance_energy,
    read_eng_flexomagnetoelectric_resonance_energy,
    read_eng_flexomagnetoexcitonic_resonance_energy,
    read_eng_flexomagnetoexcitonicmagnonic_resonance_energy,
    read_eng_flexomagnetoexcitonicpolaritonic_resonance_energy,
    read_eng_flexomagnetophononic_resonance_energy,
    read_eng_flexomagnetophononicexcitonic_resonance_energy,
    read_eng_flexomagnetophononicexcitonicmagnonic_resonance_energy,
    read_eng_flexomagnetophononicexcitonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexomagnetophononicexcitonicpolaritonic_resonance_energy,
    read_eng_flexomagnetophononicmagnonic_resonance_energy,
    read_eng_flexomagnetophononicmagnonicpolaritonic_resonance_energy,
    read_eng_flexomagnetophononicplasmonicexcitonic_resonance_energy,
    read_eng_flexomagnetophononicplasmonicexcitonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexomagnetophononicplasmonicexcitonicpolaritonic_resonance_energy,
    read_eng_flexomagnetophononicplasmonicmagnonic_resonance_energy,
    read_eng_flexomagnetophononicplasmonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexomagnetophononicplasmonicpolaritonic_resonance_energy,
    read_eng_flexomagnetophononicpolaritonic_resonance_energy,
    read_eng_flexomagnetoplasmonic_resonance_energy,
    read_eng_flexomagnetoplasmonicexciton_resonance_energy,
    read_eng_flexomagnetoplasmonicexcitonicmagnonic_resonance_energy,
    read_eng_flexomagnetoplasmonicexcitonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexomagnetoplasmonicexcitonicpolaritonic_resonance_energy,
    read_eng_flexomagnetoplasmonicmagnon_resonance_energy,
    read_eng_flexomagnetoplasmonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexomagnetoplasmonicphonon_resonance_energy,
    read_eng_flexomagnetoplasmonicpolaritonic_resonance_energy,
    read_eng_flexomagnetopolaritonic_resonance_energy,
    read_eng_flexothermal_resonance_energy, read_eng_flexothermoacoustic_resonance_energy,
    read_eng_flexothermoelectric_resonance_energy,
    read_eng_flexothermoelectroacoustic_resonance_energy,
    read_eng_flexothermoelectromagnetic_resonance_energy,
    read_eng_flexothermoelectromagnetoacoustic_resonance_energy,
    read_eng_flexothermoexcitonic_resonance_energy,
    read_eng_flexothermoexcitonicmagnonicphononicpolaritonic_resonance_energy,
    read_eng_flexothermoexcitonicphononicpolaritonic_resonance_energy,
    read_eng_flexothermoexcitonicpolaritonic_resonance_energy,
    read_eng_flexothermoexcitonmagnonpolaritonic_resonance_energy,
    read_eng_flexothermoexcitonphononmagnonpolaritonic_resonance_energy,
    read_eng_flexothermoexcitonphononpolaritonic_resonance_energy,
    read_eng_flexothermoexcitonpolaritonic_resonance_energy,
    read_eng_flexothermomagnetic_resonance_energy,
    read_eng_flexothermomagnetoacoustic_resonance_energy,
    read_eng_flexothermomagnonic_resonance_energy,
    read_eng_flexothermomagnonicphononicpolaritonic_resonance_energy,
    read_eng_flexothermomagnonicpolaritonic_resonance_energy,
    read_eng_flexothermomagnonpolaritonic_resonance_energy,
    read_eng_flexothermophononicexcitonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexothermophononicmagnonicpolaritonic_resonance_energy,
    read_eng_flexothermophononicplasmonicexcitonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexothermophononicpolaritonic_resonance_energy,
    read_eng_flexothermophononmagnonpolaritonic_resonance_energy,
    read_eng_flexothermophononpolaritonic_resonance_energy,
    read_eng_flexothermophotonic_resonance_energy,
    read_eng_flexothermoplasmonexcitonmagnonpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonexcitonphononmagnonpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonexcitonphononpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonexcitonpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonic_resonance_energy,
    read_eng_flexothermoplasmonicexcitonicmagnonicphononicpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonicexcitonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonicexcitonicphononicpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonicexcitonicpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonicmagnonicphononicpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonicmagnonicpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonicphononicpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonicpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonmagnonpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonphononmagnonpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonphononpolaritonic_resonance_energy,
    read_eng_flexothermoplasmonpolaritonic_resonance_energy, read_eng_force,
    read_eng_fsi_energy, read_eng_fxfreq, read_eng_geo, read_eng_heat_exchange,
    read_eng_helm, read_eng_helmholtz_energy, read_eng_hourglass_energy,
    read_eng_hydrostatic_pressure, read_eng_internal_energy, read_eng_internal_pressure,
    read_eng_joint_energy, read_eng_joule_heat_energy, read_eng_kinetic_energy,
    read_eng_lode_angle, read_eng_lorentz_force_energy, read_eng_magnetic_energy,
    read_eng_magnetic_hysteresis_energy, read_eng_magnetocaloric_energy,
    read_eng_magnetogalvanic_energy, read_eng_magnetorheological_energy,
    read_eng_magnetostriction_energy, read_eng_magnon_polariton_energy, read_eng_mass,
    read_eng_mass_change, read_eng_mass_energy, read_eng_max_shear,
    read_eng_maxwell_stress_energy, read_eng_moment, read_eng_monitor, read_eng_nois,
    read_eng_numerical_dissipation, read_eng_octahedral_shear, read_eng_parith,
    read_eng_phonon_polariton_energy, read_eng_photomagnetic_energy,
    read_eng_piezomagnetic_energy, read_eng_piezothermal_energy, read_eng_plasmonic_energy,
    read_eng_plastic, read_eng_plastic_work, read_eng_poynting_energy, read_eng_pressure,
    read_eng_print, read_eng_pyroelectric_energy, read_eng_pyroelectric_resonance_energy,
    read_eng_pyromagnetic_energy, read_eng_rfile, read_eng_rota, read_eng_rotc,
    read_eng_rotv, read_eng_run, read_eng_rwall_energy, read_eng_sh_thick,
    read_eng_sound_speed, read_eng_sph_energy, read_eng_spring_energy, read_eng_state,
    read_eng_stop, read_eng_strain, read_eng_strain_rate, read_eng_stress,
    read_eng_stress_tri, read_eng_sub_cycle, read_eng_surf, read_eng_surf_energy,
    read_eng_temperature, read_eng_tens, read_eng_tfile, read_eng_thermionic_energy,
    read_eng_thermoacoustic_energy, read_eng_thermoelectric_energy,
    read_eng_thermoflexoelectric_energy, read_eng_thermogalvanic_energy,
    read_eng_thermomagnetic_energy, read_eng_thermomagnetic_generator_energy,
    read_eng_thermomagnetic_resonance_energy, read_eng_thermomagnetoelectric_energy,
    read_eng_thermophononic_energy, read_eng_thermophotonic_emission_energy,
    read_eng_thermophotonic_energy, read_eng_thermoplasmonic_energy, read_eng_tot_energy,
    read_eng_total_energy, read_eng_track, read_eng_trunc, read_eng_velocity, read_eng_vers,
    read_eng_volume, read_eng_xfem_energy, read_eng_yield_stress, read_inertia_part,
    read_laminate, read_parameter, read_penta6, read_ply, read_pretensioner, read_pyra,
    read_quad, read_retractor, read_seatbelt, read_sh3n, read_shel16, read_shell, read_shfra,
    read_slipring, read_spring, read_stack, read_stamping, read_stamping_params_m58,
    read_sub_laminate, read_tetra, read_tetra10, read_tetra4, read_tria3, read_truss,
    read_tshell, read_upbeam,
)

from .materials import (  # noqa: F401
    read_eos, read_mat, read_mat_3d_comp, read_mat_3parbi, read_mat_barlat,
    read_mat_cam_clay, read_mat_cdpm2, read_mat_chang, read_mat_comp_3d, read_mat_comp_chang,
    read_mat_comp_plas, read_mat_comp_sol, read_mat_composite_plas, read_mat_compsh,
    read_mat_compso, read_mat_conc, read_mat_crasurv, read_mat_dama, read_mat_dprag2,
    read_mat_drucker, read_mat_heat, read_mat_hensel_spittel, read_mat_hill,
    read_mat_jcook_alm, read_mat_johns_cook_alm, read_mat_johns_voce_drucker, read_mat_law10,
    read_mat_law100, read_mat_law101, read_mat_law102, read_mat_law103, read_mat_law104,
    read_mat_law105, read_mat_law106, read_mat_law107, read_mat_law108, read_mat_law109,
    read_mat_law11, read_mat_law110, read_mat_law110_vegter, read_mat_law111,
    read_mat_law112, read_mat_law113, read_mat_law114, read_mat_law115, read_mat_law116,
    read_mat_law117, read_mat_law117_m182, read_mat_law119, read_mat_law12, read_mat_law120,
    read_mat_law121, read_mat_law122, read_mat_law123, read_mat_law124, read_mat_law125,
    read_mat_law126, read_mat_law127, read_mat_law128, read_mat_law129, read_mat_law13,
    read_mat_law130, read_mat_law132, read_mat_law133, read_mat_law134, read_mat_law14,
    read_mat_law15, read_mat_law151, read_mat_law158, read_mat_law16, read_mat_law163,
    read_mat_law169, read_mat_law18, read_mat_law187, read_mat_law190, read_mat_law20,
    read_mat_law21, read_mat_law22, read_mat_law23, read_mat_law25, read_mat_law26,
    read_mat_law28, read_mat_law28_m188, read_mat_law29, read_mat_law3, read_mat_law32,
    read_mat_law33, read_mat_law34, read_mat_law35, read_mat_law37, read_mat_law38,
    read_mat_law4, read_mat_law40, read_mat_law41, read_mat_law43, read_mat_law44,
    read_mat_law46, read_mat_law48, read_mat_law49, read_mat_law5, read_mat_law50,
    read_mat_law51, read_mat_law52, read_mat_law53, read_mat_law54, read_mat_law57,
    read_mat_law58, read_mat_law59, read_mat_law6, read_mat_law60, read_mat_law62,
    read_mat_law63, read_mat_law64, read_mat_law65, read_mat_law66, read_mat_law68,
    read_mat_law69, read_mat_law71, read_mat_law72, read_mat_law73, read_mat_law74,
    read_mat_law76, read_mat_law77, read_mat_law78, read_mat_law79, read_mat_law80,
    read_mat_law82, read_mat_law83, read_mat_law84, read_mat_law87, read_mat_law88,
    read_mat_law90, read_mat_law92, read_mat_law93, read_mat_law94, read_mat_law95,
    read_mat_law97, read_mat_nlocal, read_mat_nonlocal, read_mat_paper_light,
    read_mat_pfeiffer, read_mat_plas_aniso, read_mat_plas_bodne, read_mat_plas_dama,
    read_mat_plas_druck, read_mat_plas_hens, read_mat_plas_paper_light, read_mat_plas_predef,
    read_mat_plas_rate, read_mat_plas_vegter, read_mat_plas_zeril, read_mat_ragab,
    read_mat_sh_seatbelt, read_mat_spr_seatbelt, read_mat_tapo, read_mat_therm_stress,
    read_mat_tsai_wu, read_mat_vegter, read_mat_visc_lprony, read_mat_visc_prony,
    read_mat_visc_tab,
)

from .properties import (  # noqa: F401
    read_prop, read_prop_bushing, read_prop_inject1, read_prop_inject2, read_prop_joint,
    read_prop_p51, read_prop_pcompp, read_prop_rivet, read_prop_spotweld,
    read_prop_spr_bdamp, read_prop_spr_bend, read_prop_spr_tab, read_prop_spring_beam,
    read_prop_spring_elas_plas, read_prop_torsion, read_prop_tsh_comp, read_prop_tsh_orth,
    read_prop_tshell, read_prop_type10, read_prop_type11, read_prop_type12, read_prop_type13,
    read_prop_type14, read_prop_type15, read_prop_type16, read_prop_type17, read_prop_type18,
    read_prop_type19, read_prop_type20, read_prop_type21, read_prop_type22, read_prop_type23,
    read_prop_type25, read_prop_type28, read_prop_type29, read_prop_type30, read_prop_type31,
    read_prop_type32, read_prop_type33, read_prop_type34, read_prop_type35, read_prop_type36,
    read_prop_type43, read_prop_type44, read_prop_type45, read_prop_type46, read_prop_type47,
    read_prop_type48, read_prop_type5, read_prop_type51, read_prop_type54, read_prop_type6,
    read_prop_type8, read_prop_type9, read_prop_xelem,
)

from .interfaces import (  # noqa: F401
    read_def_inter, read_guided_cable, read_inter, read_inter_type21, read_inter_type23,
    read_lagmul, read_lagmul_albrecht_spatial_linkage_joint,
    read_lagmul_alexander_hybrid_spatial_linkage_joint,
    read_lagmul_algebraic_spatial_linkage_joint,
    read_lagmul_algebraic_spinor_spatial_linkage_joint,
    read_lagmul_altmann_hybrid_spatial_linkage_joint, read_lagmul_altmann_linkage_joint,
    read_lagmul_altmann_spatial_linkage_joint,
    read_lagmul_atiyah_spinor_spatial_linkage_joint,
    read_lagmul_baker_hybrid_spatial_linkage_joint, read_lagmul_baker_line_linkage_joint,
    read_lagmul_baker_linkage_joint, read_lagmul_baker_plane_linkage_joint,
    read_lagmul_baker_spatial_linkage_joint, read_lagmul_baker_symmetric_linkage_joint,
    read_lagmul_banach_spatial_linkage_joint, read_lagmul_beltrami_spatial_linkage_joint,
    read_lagmul_bennett_linkage_joint, read_lagmul_bennett_spatial_linkage_joint,
    read_lagmul_berezin_spinor_spatial_linkage_joint,
    read_lagmul_bessel_spatial_linkage_joint, read_lagmul_bevan_hybrid_spatial_linkage_joint,
    read_lagmul_birfield_joint, read_lagmul_borel_linkage_joint,
    read_lagmul_borel_spinor_spatial_linkage_joint,
    read_lagmul_bott_spinor_spatial_linkage_joint, read_lagmul_bricard_linkage_joint,
    read_lagmul_bricard_spatial_linkage_joint,
    read_lagmul_bundle_spinor_spatial_linkage_joint, read_lagmul_cable_pulley_joint,
    read_lagmul_cam_follower_joint, read_lagmul_cartan_spatial_linkage_joint,
    read_lagmul_cartan_spinor_spatial_linkage_joint,
    read_lagmul_cauchy_spatial_linkage_joint, read_lagmul_cayley_spatial_linkage_joint,
    read_lagmul_chebyshev_lambda_linkage_joint, read_lagmul_chebyshev_linkage_joint,
    read_lagmul_chen_hybrid_spatial_linkage_joint, read_lagmul_chen_linkage_joint,
    read_lagmul_chen_spatial_linkage_joint, read_lagmul_chern_spinor_spatial_linkage_joint,
    read_lagmul_chung_hybrid_spatial_linkage_joint, read_lagmul_clevis_joint,
    read_lagmul_clifford_spatial_linkage_joint,
    read_lagmul_cohomological_spatial_linkage_joint,
    read_lagmul_cohomological_spinor_spatial_linkage_joint,
    read_lagmul_conformal_spatial_linkage_joint,
    read_lagmul_conformal_spinor_spatial_linkage_joint,
    read_lagmul_connection_spinor_spatial_linkage_joint,
    read_lagmul_contact_spatial_linkage_joint,
    read_lagmul_contact_spinor_spatial_linkage_joint,
    read_lagmul_curvature_spinor_spatial_linkage_joint, read_lagmul_cycloidal_drive,
    read_lagmul_delassus_linkage_joint, read_lagmul_delassus_spatial_linkage_joint,
    read_lagmul_delta_robot_joint, read_lagmul_descartes_spatial_linkage_joint,
    read_lagmul_diesel_spatial_linkage_joint, read_lagmul_dietmaier_linkage_joint,
    read_lagmul_dietmaier_spatial_linkage_joint, read_lagmul_dietmeier_spatial_linkage_joint,
    read_lagmul_differential_gear, read_lagmul_differential_spatial_linkage_joint,
    read_lagmul_dirac_spinor_spatial_linkage_joint, read_lagmul_double_cardan_joint,
    read_lagmul_euclid_spatial_linkage_joint, read_lagmul_euler_spatial_linkage_joint,
    read_lagmul_evans_linkage_joint, read_lagmul_fermat_spatial_linkage_joint,
    read_lagmul_fibration_spinor_spatial_linkage_joint,
    read_lagmul_foliation_spinor_spatial_linkage_joint,
    read_lagmul_four_bar_crank_rocker_joint, read_lagmul_four_bar_double_crank_joint,
    read_lagmul_four_bar_double_rocker_joint, read_lagmul_fourier_spatial_linkage_joint,
    read_lagmul_franke_linkage_joint, read_lagmul_frechet_spatial_linkage_joint,
    read_lagmul_gauss_spatial_linkage_joint, read_lagmul_geneva_drive,
    read_lagmul_geneva_drive_mechanism_joint, read_lagmul_geneva_joint,
    read_lagmul_goldberg_linkage_joint, read_lagmul_goldberg_spatial_linkage_joint,
    read_lagmul_grassmann_spatial_linkage_joint,
    read_lagmul_grothendieck_spinor_spatial_linkage_joint, read_lagmul_harmonic_drive,
    read_lagmul_hart_linkage_joint, read_lagmul_hausdorff_spatial_linkage_joint,
    read_lagmul_heinrichs_hybrid_spatial_linkage_joint, read_lagmul_herve_linkage_joint,
    read_lagmul_hilbert_spatial_linkage_joint,
    read_lagmul_hirzebruch_spinor_spatial_linkage_joint, read_lagmul_hoeken_linkage_joint,
    read_lagmul_holonomy_spinor_spatial_linkage_joint,
    read_lagmul_homological_spatial_linkage_joint,
    read_lagmul_homological_spinor_spatial_linkage_joint, read_lagmul_hooke_joint,
    read_lagmul_hunt_linkage_joint, read_lagmul_hunt_spatial_linkage_joint,
    read_lagmul_hunt_special_spatial_linkage_joint, read_lagmul_hypocyclic_linkage_joint,
    read_lagmul_jacobi_spinor_spatial_linkage_joint, read_lagmul_jansen_linkage_joint,
    read_lagmul_kahler_spinor_spatial_linkage_joint, read_lagmul_kempe_linkage_joint,
    read_lagmul_kirkpatrick_hybrid_spatial_linkage_joint,
    read_lagmul_kirson_spatial_linkage_joint, read_lagmul_klann_linkage_joint,
    read_lagmul_kong_linkage_joint, read_lagmul_konnok_spatial_linkage_joint,
    read_lagmul_kostant_spinor_spatial_linkage_joint, read_lagmul_krames_linkage_joint,
    read_lagmul_krause_hybrid_spatial_linkage_joint,
    read_lagmul_krause_spatial_linkage_joint, read_lagmul_lagrange_spatial_linkage_joint,
    read_lagmul_laplace_spatial_linkage_joint, read_lagmul_lead_screw_joint,
    read_lagmul_leibniz_spatial_linkage_joint, read_lagmul_lobachevsky_spatial_linkage_joint,
    read_lagmul_majorana_spinor_spatial_linkage_joint,
    read_lagmul_maverick_hybrid_spatial_linkage_joint,
    read_lagmul_maverick_spatial_linkage_joint, read_lagmul_minkowski_spatial_linkage_joint,
    read_lagmul_monodromy_spinor_spatial_linkage_joint, read_lagmul_myard_linkage_joint,
    read_lagmul_myard_spatial_linkage_joint, read_lagmul_newton_spatial_linkage_joint,
    read_lagmul_oldham_coupling, read_lagmul_orbifold_spinor_spatial_linkage_joint,
    read_lagmul_pantograph_linkage_joint, read_lagmul_parallel_axis_joint,
    read_lagmul_parallelogram_joint, read_lagmul_pascal_spatial_linkage_joint,
    read_lagmul_peaucellier_linkage_joint, read_lagmul_pfurner_spatial_linkage_joint,
    read_lagmul_phillips_spatial_linkage_joint, read_lagmul_pin_in_slot_joint,
    read_lagmul_poincare_spatial_linkage_joint, read_lagmul_poisson_spatial_linkage_joint,
    read_lagmul_poisson_spinor_spatial_linkage_joint,
    read_lagmul_projective_spatial_linkage_joint,
    read_lagmul_projective_spinor_spatial_linkage_joint, read_lagmul_rack_pinion,
    read_lagmul_riemann_spatial_linkage_joint, read_lagmul_roberts_linkage_joint,
    read_lagmul_rzeppa_joint, read_lagmul_sarrus_linkage_joint,
    read_lagmul_sarrus_spatial_linkage_joint, read_lagmul_schatz_linkage_joint,
    read_lagmul_scheme_spinor_spatial_linkage_joint, read_lagmul_schmidt_coupling,
    read_lagmul_scissor_mechanism_joint, read_lagmul_scotch_yoke,
    read_lagmul_scotch_yoke_mechanism_joint, read_lagmul_scott_russell_linkage_joint,
    read_lagmul_screw_joint, read_lagmul_screw_nut_joint,
    read_lagmul_serre_spinor_spatial_linkage_joint,
    read_lagmul_sheaf_spinor_spatial_linkage_joint,
    read_lagmul_slider_rocker_inversion_joint, read_lagmul_slider_slot_joint,
    read_lagmul_sobolev_spatial_linkage_joint,
    read_lagmul_souriau_spinor_spatial_linkage_joint, read_lagmul_spherical_wrist_joint,
    read_lagmul_spinorial_spatial_linkage_joint,
    read_lagmul_stack_spinor_spatial_linkage_joint, read_lagmul_stephenson_linkage_joint,
    read_lagmul_stevens_hybrid_spatial_linkage_joint,
    read_lagmul_stevens_spatial_linkage_joint,
    read_lagmul_stratification_spinor_spatial_linkage_joint,
    read_lagmul_sturgess_hybrid_spatial_linkage_joint,
    read_lagmul_sturgess_spatial_linkage_joint, read_lagmul_swash_plate_joint,
    read_lagmul_sylvester_kempe_linkage_joint, read_lagmul_sylvester_spatial_linkage_joint,
    read_lagmul_symplectic_spatial_linkage_joint,
    read_lagmul_symplectic_spinor_spatial_linkage_joint,
    read_lagmul_tchebychev_spatial_linkage_joint, read_lagmul_thompson_coupling,
    read_lagmul_topological_spatial_linkage_joint,
    read_lagmul_topological_spinor_spatial_linkage_joint,
    read_lagmul_topos_spinor_spatial_linkage_joint, read_lagmul_torque_split_gear,
    read_lagmul_torsion_spinor_spatial_linkage_joint, read_lagmul_tracta_joint,
    read_lagmul_transfer_case, read_lagmul_tripod_ball_joint, read_lagmul_tripod_joint,
    read_lagmul_waldron_hybrid_spatial_linkage_joint, read_lagmul_waldron_linkage_joint,
    read_lagmul_waldron_spatial_linkage_joint, read_lagmul_watt_beam_engine_joint,
    read_lagmul_watt_linkage_joint, read_lagmul_watt_parallel_motion_joint,
    read_lagmul_weiss_joint, read_lagmul_whitworth_quick_return_joint,
    read_lagmul_wobble_plate_mechanism_joint, read_lagmul_wobble_yoke_joint,
    read_lagmul_wohlhart_hybrid_linkage_joint,
    read_lagmul_wohlhart_hybrid_spatial_linkage_joint, read_lagmul_wohlhart_linkage_joint,
    read_lagmul_wohlhart_spatial_linkage_joint, read_lagmul_wunderlich_linkage_joint,
    read_lagmul_wunderlich_spatial_linkage_joint, read_subinter,
)

from .constraints import (  # noqa: F401
    read_dynain, read_dynain_dt, read_gjoint, read_mpc, read_rbe2, read_rbe3, read_rbody,
    read_rbody_stop, read_rlink, read_rwall, read_rwall_therm, read_spcnd,
)

from .loads import (  # noqa: F401
    read_centri, read_cload, read_convec, read_convec_heat_m202, read_flux, read_grav,
    read_heat, read_heat_rad_cav, read_impflux, read_laser, read_load, read_load_centri,
    read_load_pcyl, read_load_pressure, read_pblast, read_pcyl, read_pfluid, read_pload,
    read_preload, read_preload_axial, read_preload_bolt, read_radiation,
    read_radiation_heat_m202,
)

from .conditions import (  # noqa: F401
    _IMP_DIRS, _IMP_DOF, read_bcs, read_bcs_cyclic, read_bcs_nrf, read_bcs_wall, read_ebcs,
    read_ebcs_cyclic, read_ebcs_fluxout, read_ebcs_gradp0, read_ebcs_inip, read_ebcs_iniv,
    read_ebcs_inlet, read_ebcs_monvol, read_ebcs_normv, read_ebcs_nrf, read_ebcs_periodic,
    read_ebcs_pres, read_ebcs_propellant, read_ebcs_valv, read_ebcs_vel, read_impacc,
    read_impdisp, read_impdisp_fgeo, read_imptemp, read_impvel, read_impvel_fgeo,
    read_inibea, read_inibri, read_inibri_eref, read_inicrack, read_inigrav, read_inimap,
    read_inimap1d, read_inimap2d, read_inimap3d, read_iniqua, read_inish3, read_inishe,
    read_inisphcel, read_inispr, read_inista, read_init, read_initemp, read_initru,
    read_inivel, read_inivel_fvm, read_inivel_node, read_inivol, split_imposed_card,
)

from .groups import (  # noqa: F401
    _GR_FAMILIES, read_det, read_dfs, read_gr_elem, read_grnod, read_includedyna, read_mid,
    read_part, read_pid, read_random, read_random_stochastic_m37, read_set, read_subdomain,
    read_submodel, read_xref,
)

from .output import (  # noqa: F401
    read_anim_dt, read_cluster, read_gauge, read_gauge_point, read_h3d, read_sensor,
    read_sensor_beam_force, read_sensor_beam_strain, read_sensor_cross_section,
    read_sensor_energy_error, read_sensor_energy_ratio, read_sensor_gap,
    read_sensor_mass_ratio, read_sensor_pressure, read_sensor_rupture, read_sensor_shear,
    read_sensor_shell_force, read_sensor_shell_strain, read_sensor_solid_force,
    read_sensor_solid_strain, read_sensor_spring, read_sensor_spring_angular_acceleration,
    read_sensor_spring_angular_velocity, read_sensor_spring_axial,
    read_sensor_spring_axial_crackle_rate, read_sensor_spring_axial_energy,
    read_sensor_spring_axial_snap_rate, read_sensor_spring_bend,
    read_sensor_spring_bending_acceleration, read_sensor_spring_bending_acceleration_rate,
    read_sensor_spring_bending_crackle_rate, read_sensor_spring_bending_drift_rate,
    read_sensor_spring_bending_drop_rate, read_sensor_spring_bending_energy,
    read_sensor_spring_bending_jerk, read_sensor_spring_bending_jerk_rate,
    read_sensor_spring_bending_lock_rate, read_sensor_spring_bending_pop_rate,
    read_sensor_spring_bending_rate_of_change, read_sensor_spring_bending_shot_rate,
    read_sensor_spring_bending_snap_rate, read_sensor_spring_bending_surge_rate,
    read_sensor_spring_contact_energy, read_sensor_spring_coupled_crackle_rate,
    read_sensor_spring_coupled_pop_rate, read_sensor_spring_coupling_energy,
    read_sensor_spring_damping_energy, read_sensor_spring_defl, read_sensor_spring_density,
    read_sensor_spring_energy, read_sensor_spring_entropy, read_sensor_spring_ext_work,
    read_sensor_spring_force_impulse, read_sensor_spring_force_rate,
    read_sensor_spring_friction_energy, read_sensor_spring_hourglass_energy,
    read_sensor_spring_kinetic_energy, read_sensor_spring_mass_change,
    read_sensor_spring_mass_energy, read_sensor_spring_moment_impulse,
    read_sensor_spring_moment_rate, read_sensor_spring_normal_acceleration,
    read_sensor_spring_normal_acceleration_jerk, read_sensor_spring_normal_acceleration_rate,
    read_sensor_spring_normal_crackle_rate, read_sensor_spring_normal_drift_rate,
    read_sensor_spring_normal_drop_rate, read_sensor_spring_normal_jerk,
    read_sensor_spring_normal_jerk_rate, read_sensor_spring_normal_lock_rate,
    read_sensor_spring_normal_pop_rate, read_sensor_spring_normal_shot_rate,
    read_sensor_spring_normal_snap_rate, read_sensor_spring_normal_surge_rate,
    read_sensor_spring_normal_work, read_sensor_spring_numerical_dissipation,
    read_sensor_spring_pinching_energy, read_sensor_spring_plastic_work,
    read_sensor_spring_pressure, read_sensor_spring_resultant_acceleration,
    read_sensor_spring_resultant_jerk, read_sensor_spring_rot, read_sensor_spring_rota,
    read_sensor_spring_rotational_work, read_sensor_spring_rotv, read_sensor_spring_shear,
    read_sensor_spring_shear_acceleration, read_sensor_spring_shear_energy,
    read_sensor_spring_shear_jerk, read_sensor_spring_shear_work,
    read_sensor_spring_sound_speed, read_sensor_spring_strain_energy,
    read_sensor_spring_temperature, read_sensor_spring_thermal_dissipation,
    read_sensor_spring_torsion, read_sensor_spring_torsional_acceleration,
    read_sensor_spring_torsional_acceleration_rate,
    read_sensor_spring_torsional_crackle_rate, read_sensor_spring_torsional_drift_rate,
    read_sensor_spring_torsional_drop_rate, read_sensor_spring_torsional_energy,
    read_sensor_spring_torsional_jerk, read_sensor_spring_torsional_jerk_rate,
    read_sensor_spring_torsional_lock_rate, read_sensor_spring_torsional_pop_rate,
    read_sensor_spring_torsional_rate, read_sensor_spring_torsional_rate_of_change,
    read_sensor_spring_torsional_shot_rate, read_sensor_spring_torsional_snap_rate,
    read_sensor_spring_torsional_surge_rate, read_sensor_spring_tot_energy,
    read_sensor_spring_total_acceleration_jerk, read_sensor_spring_total_acceleration_rate,
    read_sensor_spring_total_angular_acceleration,
    read_sensor_spring_total_angular_acceleration_rate,
    read_sensor_spring_total_angular_crackle_rate,
    read_sensor_spring_total_angular_drift_rate, read_sensor_spring_total_angular_drop_rate,
    read_sensor_spring_total_angular_jerk, read_sensor_spring_total_angular_lock_rate,
    read_sensor_spring_total_angular_pop_rate,
    read_sensor_spring_total_angular_rate_of_change,
    read_sensor_spring_total_angular_shot_rate, read_sensor_spring_total_angular_snap_rate,
    read_sensor_spring_total_angular_surge_rate, read_sensor_spring_total_crackle_rate,
    read_sensor_spring_total_drift_rate, read_sensor_spring_total_drop_rate,
    read_sensor_spring_total_force, read_sensor_spring_total_jerk_rate,
    read_sensor_spring_total_lock_rate, read_sensor_spring_total_moment,
    read_sensor_spring_total_pop_rate, read_sensor_spring_total_shot_rate,
    read_sensor_spring_total_snap_rate, read_sensor_spring_total_strain_energy,
    read_sensor_spring_total_surge_rate, read_sensor_spring_total_work,
    read_sensor_spring_translational_work, read_sensor_spring_transverse_acceleration_jerk,
    read_sensor_spring_transverse_acceleration_rate,
    read_sensor_spring_transverse_crackle_rate, read_sensor_spring_transverse_drift_rate,
    read_sensor_spring_transverse_drop_rate, read_sensor_spring_transverse_jerk_rate,
    read_sensor_spring_transverse_lock_rate, read_sensor_spring_transverse_pop_rate,
    read_sensor_spring_transverse_shot_rate, read_sensor_spring_transverse_snap_rate,
    read_sensor_spring_transverse_surge_rate, read_sensor_spring_volume,
    read_sensor_spring_volumetric_energy, read_sensor_spring_yield_stress,
    read_sensor_truss_force, read_sensor_truss_strain, read_sensor_work_ratio, read_th,
    read_th_subs, read_th_title, read_thpart_group,
)

from .misc import (  # noqa: F401
    _LAYOUTS, _cut_floats, _cut_ints, _direction, _f, _fixed_data, _fixed_vals, _floats,
    _fval, _hourglass_defaults, _i, _id_list, _is_numeric_card, _ival, _law2_iflag1_to_abn,
    _nondefault, _read_elems, _read_imposed, _read_mat_modifier, _read_reference_system,
    _safe_float, _safe_int, _skew_dir, _split_fixed, _title_and_data, _unit_fields,
    _warn_ignored, cut, read_accel, read_activ, read_admas, read_admas_non_uniform,
    read_admesh, read_admesh_global, read_airbag, read_airbag_injector, read_airbag_venthole,
    read_ale, read_ale_bcs, read_ale_close, read_ale_done, read_ale_link, read_ale_muscl,
    read_ale_solver, read_alecfdsph, read_altdoctag, read_ams, read_analy, read_arch,
    read_ball_joint, read_begin, read_belt_pulley_joint, read_bem, read_bevel_gear_joint,
    read_caa, read_cardan_joint, read_checksum, read_cnode, read_cv_joint, read_damp,
    read_damp_funct, read_damp_inter, read_damp_part, read_damp_range, read_damp_vrel,
    read_ddw, read_diff, read_distance_joint, read_dt_brick, read_dt_inter_del,
    read_dt_noda_cfl, read_dttsh, read_eig, read_end, read_endsub, read_epicyclic_gear_joint,
    read_eref, read_euler, read_extlnk, read_fail, read_fail_alter, read_fail_bai_wierzbicki,
    read_fail_bamman, read_fail_bao_wierzbicki, read_fail_biquad_aniso, read_fail_bonora,
    read_fail_chaboche, read_fail_cockcroft, read_fail_cockcroft_latham, read_fail_cohesive,
    read_fail_composite, read_fail_drucker, read_fail_drucker_prager, read_fail_emc,
    read_fail_energy, read_fail_energy_density, read_fail_energy_ratio,
    read_fail_extended_mohr, read_fail_fractal, read_fail_freudenthal, read_fail_gene1,
    read_fail_ghosh, read_fail_gologanu, read_fail_griffith, read_fail_gtn, read_fail_gurson,
    read_fail_hashin, read_fail_hc, read_fail_hc_dsse, read_fail_hencky, read_fail_hill,
    read_fail_hockett_sherby, read_fail_hollomon, read_fail_hoop, read_fail_hosford_coulomb,
    read_fail_inievo, read_fail_jh2, read_fail_johnson_cook, read_fail_kim_baek,
    read_fail_lad_aniso, read_fail_lad_anisotropic_plasticity, read_fail_lad_couple,
    read_fail_lad_couple_core_cracking_rate, read_fail_lad_couple_core_crushing_rate,
    read_fail_lad_couple_core_debonding_rate,
    read_fail_lad_couple_core_delamination_cracking_rate,
    read_fail_lad_couple_core_delamination_rate, read_fail_lad_couple_core_shearing_rate,
    read_fail_lad_couple_creep, read_fail_lad_couple_crush_rate, read_fail_lad_couple_damage,
    read_fail_lad_couple_damage_viscoelasticity,
    read_fail_lad_couple_delamination_microdebonding_rate,
    read_fail_lad_couple_delamination_rate, read_fail_lad_couple_dynamic_crush,
    read_fail_lad_couple_facesheet_core_debonding_rate,
    read_fail_lad_couple_facesheet_core_shearing_rate,
    read_fail_lad_couple_fiber_compression_crushing_rate,
    read_fail_lad_couple_fiber_compression_kinking_rate,
    read_fail_lad_couple_fiber_crushing_rate, read_fail_lad_couple_fiber_kinking_rate,
    read_fail_lad_couple_fiber_matrix_debonding_rate,
    read_fail_lad_couple_fiber_micro_buckling_rate,
    read_fail_lad_couple_fiber_splitting_rate,
    read_fail_lad_couple_fiber_tension_rupture_rate,
    read_fail_lad_couple_honeycomb_core_crushing_rate,
    read_fail_lad_couple_honeycomb_core_shearing_rate,
    read_fail_lad_couple_interlaminar_normal_peeling_rate,
    read_fail_lad_couple_interlaminar_shear_delamination_rate,
    read_fail_lad_couple_interlaminar_shear_rate,
    read_fail_lad_couple_interlaminar_tension_rate,
    read_fail_lad_couple_matrix_cracking_rate,
    read_fail_lad_couple_matrix_micro_crushing_rate,
    read_fail_lad_couple_matrix_micro_fissuring_rate,
    read_fail_lad_couple_matrix_microcracking_rate,
    read_fail_lad_couple_matrix_shear_degradation_rate,
    read_fail_lad_couple_microbuckling_rate, read_fail_lad_couple_plasticity,
    read_fail_lad_couple_ply_micro_cracking_rate, read_fail_lad_couple_viscoplasticity,
    read_fail_lad_coupled_core_microbuckling_rate,
    read_fail_lad_coupled_core_microcracking_rate,
    read_fail_lad_coupled_core_microyielding_rate,
    read_fail_lad_coupled_delamination_microcracking_rate,
    read_fail_lad_coupled_delamination_microdebonding_rate,
    read_fail_lad_coupled_fiber_compression_failure_rate,
    read_fail_lad_coupled_fiber_kinking_failure_rate,
    read_fail_lad_coupled_fiber_tension_rupture_rate,
    read_fail_lad_coupled_interlaminar_shear_failure_rate,
    read_fail_lad_coupled_interlaminar_tension_failure_rate,
    read_fail_lad_coupled_matrix_crushing_failure_rate,
    read_fail_lad_coupled_matrix_microcracking_failure_rate,
    read_fail_lad_coupled_matrix_shear_degradation_rate, read_fail_lad_creep,
    read_fail_lad_dama, read_fail_lad_delam, read_fail_lad_diffuse_damage,
    read_fail_lad_dynamic_core_cracking_rate,
    read_fail_lad_dynamic_core_crushing_failure_rate,
    read_fail_lad_dynamic_core_crushing_rate, read_fail_lad_dynamic_core_debonding_rate,
    read_fail_lad_dynamic_core_delamination_cracking_rate,
    read_fail_lad_dynamic_core_delamination_rate,
    read_fail_lad_dynamic_core_microbuckling_rate,
    read_fail_lad_dynamic_core_microcracking_rate,
    read_fail_lad_dynamic_core_microyielding_rate, read_fail_lad_dynamic_core_shearing_rate,
    read_fail_lad_dynamic_core_tearing_rate, read_fail_lad_dynamic_crush_rate,
    read_fail_lad_dynamic_delamination_microcracking_rate,
    read_fail_lad_dynamic_delamination_microdebonding_rate,
    read_fail_lad_dynamic_delamination_rate,
    read_fail_lad_dynamic_facesheet_core_debonding_rate,
    read_fail_lad_dynamic_facesheet_core_shearing_rate,
    read_fail_lad_dynamic_fiber_compression_crushing_rate,
    read_fail_lad_dynamic_fiber_compression_failure_rate,
    read_fail_lad_dynamic_fiber_compression_kinking_rate,
    read_fail_lad_dynamic_fiber_crushing_rate,
    read_fail_lad_dynamic_fiber_kinking_failure_rate,
    read_fail_lad_dynamic_fiber_kinking_rate,
    read_fail_lad_dynamic_fiber_matrix_debonding_rate,
    read_fail_lad_dynamic_fiber_micro_buckling_rate,
    read_fail_lad_dynamic_fiber_splitting_rate,
    read_fail_lad_dynamic_fiber_tension_rupture_rate,
    read_fail_lad_dynamic_honeycomb_core_crushing_rate,
    read_fail_lad_dynamic_honeycomb_core_shearing_rate,
    read_fail_lad_dynamic_interlaminar_normal_peeling_rate,
    read_fail_lad_dynamic_interlaminar_shear_delamination_rate,
    read_fail_lad_dynamic_interlaminar_shear_failure_rate,
    read_fail_lad_dynamic_interlaminar_shear_rate,
    read_fail_lad_dynamic_interlaminar_tension_failure_rate,
    read_fail_lad_dynamic_interlaminar_tension_rate,
    read_fail_lad_dynamic_matrix_cracking_rate,
    read_fail_lad_dynamic_matrix_crushing_failure_rate,
    read_fail_lad_dynamic_matrix_micro_crushing_rate,
    read_fail_lad_dynamic_matrix_micro_fissuring_rate,
    read_fail_lad_dynamic_matrix_microcracking_failure_rate,
    read_fail_lad_dynamic_matrix_microcracking_rate,
    read_fail_lad_dynamic_matrix_shear_degradation_rate,
    read_fail_lad_dynamic_microbuckling_rate, read_fail_lad_dynamic_ply_micro_cracking_rate,
    read_fail_lad_evr, read_fail_lad_fatigue, read_fail_lad_fib,
    read_fail_lad_fiber_compression_rate, read_fail_lad_fiber_kinking,
    read_fail_lad_fiber_kinking_rate, read_fail_lad_fiber_matrix_debond_rate,
    read_fail_lad_fiber_matrix_debonding, read_fail_lad_fiber_matrix_interaction,
    read_fail_lad_fiber_tension_rate, read_fail_lad_fracture, read_fail_lad_hygrothermal,
    read_fail_lad_inplane_shear, read_fail_lad_inplane_shear_rate, read_fail_lad_inter,
    read_fail_lad_interfacial_delamination, read_fail_lad_interfacial_delamination_rate,
    read_fail_lad_interlaminar_shear, read_fail_lad_micro,
    read_fail_lad_micro_delamination_rate, read_fail_lad_nonlocal_gradient,
    read_fail_lad_nonlocal_gradient_rate, read_fail_lad_str, read_fail_lad_tc_asymmetry,
    read_fail_lad_trans_isotropic, read_fail_lad_transverse_compression,
    read_fail_lad_transverse_compression_rate, read_fail_lad_transverse_core_cracking_rate,
    read_fail_lad_transverse_core_crushing_rate,
    read_fail_lad_transverse_core_debonding_rate,
    read_fail_lad_transverse_core_delamination_cracking_rate,
    read_fail_lad_transverse_core_delamination_rate,
    read_fail_lad_transverse_core_microbuckling_rate,
    read_fail_lad_transverse_core_microcracking_rate,
    read_fail_lad_transverse_core_microyielding_rate,
    read_fail_lad_transverse_core_shearing_rate, read_fail_lad_transverse_crush_rate,
    read_fail_lad_transverse_delamination_microcracking_rate,
    read_fail_lad_transverse_delamination_microdebonding_rate,
    read_fail_lad_transverse_delamination_rate,
    read_fail_lad_transverse_facesheet_core_debonding_rate,
    read_fail_lad_transverse_facesheet_core_shearing_rate,
    read_fail_lad_transverse_fiber_compression_crushing_rate,
    read_fail_lad_transverse_fiber_compression_failure_rate,
    read_fail_lad_transverse_fiber_compression_kinking_rate,
    read_fail_lad_transverse_fiber_crushing_rate,
    read_fail_lad_transverse_fiber_kinking_failure_rate,
    read_fail_lad_transverse_fiber_kinking_rate,
    read_fail_lad_transverse_fiber_matrix_debonding_rate,
    read_fail_lad_transverse_fiber_micro_buckling_rate,
    read_fail_lad_transverse_fiber_splitting_rate,
    read_fail_lad_transverse_fiber_tension_rupture_rate,
    read_fail_lad_transverse_honeycomb_core_crushing_rate,
    read_fail_lad_transverse_honeycomb_core_shearing_rate,
    read_fail_lad_transverse_interlaminar_normal_peeling_rate,
    read_fail_lad_transverse_interlaminar_shear_delamination_rate,
    read_fail_lad_transverse_interlaminar_shear_failure_rate,
    read_fail_lad_transverse_interlaminar_shear_rate,
    read_fail_lad_transverse_interlaminar_tension_failure_rate,
    read_fail_lad_transverse_interlaminar_tension_rate,
    read_fail_lad_transverse_matrix_cracking_rate,
    read_fail_lad_transverse_matrix_crushing_failure_rate,
    read_fail_lad_transverse_matrix_micro_crushing_rate,
    read_fail_lad_transverse_matrix_micro_fissuring_rate,
    read_fail_lad_transverse_matrix_microcracking_failure_rate,
    read_fail_lad_transverse_matrix_microcracking_rate,
    read_fail_lad_transverse_matrix_shear_degradation_rate,
    read_fail_lad_transverse_microbuckling_rate,
    read_fail_lad_transverse_ply_micro_cracking_rate,
    read_fail_lad_transverse_shear_interaction,
    read_fail_lad_transverse_shear_interaction_rate, read_fail_lad_transverse_tension,
    read_fail_lad_transverse_tension_rate, read_fail_lad_visc, read_fail_lad_visco_damage,
    read_fail_lad_visco_fatigue, read_fail_lad_visco_plast, read_fail_lemaitre,
    read_fail_lemaitre_damage, read_fail_lou_huhn, read_fail_lou_huo, read_fail_ludwik,
    read_fail_lusas, read_fail_maxstress, read_fail_mohr, read_fail_mohr_coulomb,
    read_fail_mullins, read_fail_norton, read_fail_nxt, read_fail_ortho,
    read_fail_orthstrain, read_fail_oyane, read_fail_pu, read_fail_puck, read_fail_rht,
    read_fail_rice_tracey, read_fail_ritchie, read_fail_rousselier, read_fail_rtcl,
    read_fail_sahraei, read_fail_sn_curve, read_fail_snow, read_fail_spalling,
    read_fail_spalling_cut, read_fail_swift, read_fail_swift_voce, read_fail_syazwan,
    read_fail_tab1, read_fail_tab2, read_fail_tab3, read_fail_tabulated_plasticity,
    read_fail_tbid, read_fail_tbutcher, read_fail_tensstrain, read_fail_tuler_butcher,
    read_fail_tvergaard, read_fail_user, read_fail_visco, read_fail_visual, read_fail_voce,
    read_fail_voids, read_fail_weibull, read_fail_wierzbicki, read_fail_wilkins,
    read_fail_wilkins_cumulative, read_fail_wood, read_flow, read_fric_orient, read_friction,
    read_func2d, read_funct, read_funct_python, read_funct_smooth, read_fxbody, read_gear,
    read_gimbal_joint, read_hypoid_gear_joint, read_implicit, read_inline_joint,
    read_intthick, read_ioflag, read_leak, read_madymo, read_madymo_exfem, read_madymo_link,
    read_memory, read_merge, read_merge_rbody, read_monvol, read_monvol_airbag,
    read_monvol_area, read_monvol_comm, read_monvol_commu, read_monvol_commu_type5,
    read_monvol_fvmbag1, read_monvol_fvmbag2, read_monvol_gas, read_monvol_lfluid,
    read_monvol_part, read_monvol_pres, read_move_funct, read_nbcs, read_nonlocal,
    read_oldham_joint, read_perpendicular_joint, read_perturb, read_pin_joint,
    read_planar_joint, read_preproc_metadata, read_rack, read_rack_pinion_joint, read_refsta,
    read_relax, read_rigid_joint, read_screw_joint, read_sect, read_sect_circle,
    read_sect_paral, read_slider_joint, read_slot_joint, read_sms, read_sph, read_sph_flow,
    read_sph_inout, read_sph_reserve, read_sphbcs, read_sphcel, read_sphglo, read_spmd,
    read_state, read_state_dt, read_str_file, read_subset, read_subtitle, read_table,
    read_table_block, read_title, read_tripod_joint, read_unit, read_upwind, read_userwi,
    read_visc, read_visc_plas, read_worm_gear_joint, read_xfem,
)
